---

- name: Create config file
  template: src=redis.conf.j2 dest={{ deploy_base }}/{{ main_name }}/redis.conf owner=redis group=redis mode=0644
  tags: configuration

- name: Stop redis
  service: name=redis state=stopped

- name: Start redis
  service: name=redis state=started

- include: sentinel.yml
- include: twemproxy.yml
- include: beholder.yml
  notify:
  - Restart redis
  - Restart sentinel
  - Restart twemproxy
  - Restart beholder
